// ─── Historical Disruption Frequency Service ──────────────────────────────────
// Loads pre-computed disruption frequency data from CSV (generated by
// ml/generate_historical_data.py from IMD rainfall + CWC flood records).
//
// This approach avoids hardcoded lookup tables — the CSV can be regenerated
// whenever new IMD data is published, without code changes.

const fs = require('fs');
const path = require('path');

const CSV_PATH = path.join(__dirname, '..', '..', 'mnt', 'historical_disruption.csv');

// Parse CSV into nested lookup: DISRUPTION_DATA[city][month] = { ... }
const DISRUPTION_DATA = {};

function loadData() {
  try {
    const raw = fs.readFileSync(CSV_PATH, 'utf-8');
    const lines = raw.trim().split('\n');
    const headers = lines[0].split(',');

    for (let i = 1; i < lines.length; i++) {
      const values = lines[i].split(',');
      const row = {};
      headers.forEach((h, idx) => { row[h.trim()] = values[idx]?.trim(); });

      const city = row.city;
      const month = parseInt(row.month);
      if (!DISRUPTION_DATA[city]) DISRUPTION_DATA[city] = {};
      DISRUPTION_DATA[city][month] = {
        avgRainfallMm:     parseFloat(row.avg_rainfall_mm) || 0,
        floodEventsAvg:    parseFloat(row.flood_events_avg) || 0,
        disruptionDaysAvg: parseFloat(row.disruption_days_avg) || 0,
        triggerProbability: parseFloat(row.trigger_probability) || 0,
      };
    }

    const cityCount = Object.keys(DISRUPTION_DATA).length;
    console.log(`📊 Historical disruption data loaded: ${cityCount} cities, ${lines.length - 1} records`);
  } catch (err) {
    console.warn(`⚠️ Historical disruption CSV not found at ${CSV_PATH}. Using fallback defaults.`);
  }
}

// Load on module init
loadData();

/**
 * Get historical disruption risk for a specific city and month.
 * @param {string} city - City name (lowercase)
 * @param {number} month - Month (1-12)
 * @returns {{ avgRainfallMm, floodEventsAvg, disruptionDaysAvg, triggerProbability }}
 */
function getHistoricalRisk(city, month) {
  const normalizedCity = (city || '').toLowerCase().trim();
  const m = parseInt(month) || (new Date().getMonth() + 1);

  if (DISRUPTION_DATA[normalizedCity]?.[m]) {
    return DISRUPTION_DATA[normalizedCity][m];
  }

  // Fallback defaults when city/month not in dataset
  return {
    avgRainfallMm: 50,
    floodEventsAvg: 0.1,
    disruptionDaysAvg: 1,
    triggerProbability: 0.03,
  };
}

/**
 * Get the seasonal trigger probability for a city (current month).
 * Used by premiumService to calibrate surge loading.
 * @param {string} city
 * @returns {number} Probability [0, 1]
 */
function getSeasonalTriggerProbability(city) {
  const month = new Date().getMonth() + 1;
  return getHistoricalRisk(city, month).triggerProbability;
}

/**
 * Get the full 12-month disruption profile for a city.
 * Used by the admin dashboard to visualize seasonal risk.
 * @param {string} city
 * @returns {Array<{ month, avgRainfallMm, floodEventsAvg, disruptionDaysAvg, triggerProbability }>}
 */
function getCityDisruptionProfile(city) {
  const normalizedCity = (city || '').toLowerCase().trim();
  const profile = [];

  for (let m = 1; m <= 12; m++) {
    const data = getHistoricalRisk(normalizedCity, m);
    profile.push({ month: m, ...data });
  }

  return profile;
}

module.exports = {
  getHistoricalRisk,
  getSeasonalTriggerProbability,
  getCityDisruptionProfile,
  DISRUPTION_DATA,
};
